language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

branches:
  except:
    - singleton

before-script:
  - /home/travis/.phpenv/versions/5.6/bin/composer self-update

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2d18bca3176fc93f9924
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
